### ISSUE TITLE
vlib/vpp: Replace linux epoll with equivalent kqueue or libevent2

### ISSUE THREAD

**Issue by ftk-ntq** [ftk-ntq/vpp#11]
There is some uses with epoll for events.
In FreeBSD kqueue provides similar functionality than the epoll.
libevent2 is a library that provides support for epoll, kqueue, etc and aims to be platform independant

(cb669a06092e2f521eb602b85b3076e296f18320)
(https://github.com/ftk-ntq/vpp/commit/943b6bd97b1a3c9bf5754f4c4e672d4bc4f71187)
(https://github.com/ftk-ntq/vpp/commit/f988f025d7616006df9fd378fe861097723a47af)

**Comment by rdlr** [comment]
Used the [epoll-shim](https://www.freshports.org/devel/libepoll-shim/) library to resolve this issue.
Epoll-shim is a library that implements epoll on top of kqueue. Its been used to port libinput, libevdev, Wayland etc. to FreeBSD
